name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'

  path:  # id of input
    description: 'path'
    required: true
    default: |
      backstop_data/html_report/
      backstop_data/bitmaps_test/
      backstop_data/bitmaps_reference/

outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'composite'
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - run: ${{ github.action_path }}/install.sh
      shell: bash
      working-directory: ${{ github.action_path }}
    - run: ${{ github.action_path }}/run-test.sh
      shell: bash
      working-directory: ${{ github.action_path }}
    - run: ${{ github.action_path }}/archive-result.sh
      shell: bash
      working-directory: ${{ github.action_path }}

#    - run: ${{ github.action_path }}/deploy-to-netlify.sh
#      shell: bash
#      working-directory: backstop_data
#      env:
#        NETLIFY_SITE_ID: aa005b39-2e0f-4e85-9e0d-2cb260657b8a

