name: 'Backstop test'
description: 'Run backstop test in Docker container'
inputs:
  backstop-data-folder:  # id of input
    description: 'Folder which contains the backstop_data'
    required: false
    default: backstop_data
  backstop-config:
    description: 'location of backstop.json'
    required: false
    default: backstop.json
  backstop-version:
    description: 'version'
    required: false
    default: 5.1.0
  report-name:
    description: "Name for the report artifact"
    required: false
    default: Backstop Test Report

runs:
  using: 'node12'
  main: 'dist/index.js'


