name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  path:  # id of input
    description: 'path'
    required: false
    default: action/backstop_data
  if-no-files-found:  # id of input
    required: false
    default: error
  name:  # id of input
    required: false
    default: backstop report

runs:
  using: 'node12'
  main: 'index.js'

