name: 'Approve Backstop Images'
description: 'Action which checks out artifact and approves the changes'
inputs:
  backstop-folder:
    description: 'folder'
    required: false
    default: backstop_data
  backstop-version:
    description: 'version'
    required: false
    default: 5.1.0
  token:
    description: 'github api token'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'

