name: Approve failed backstop test

on:
  issue_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Approve backstop test
    steps:
      - uses: actions/checkout@v2
#        todo: only do this when comment contains keyword
      - uses: ./approve-images
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
