name: Approve failed backstop test

on:
  issue_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Approve backstop test
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: approve-images # todo: this should happen inside action itself
      - uses: ./approve-images


