name: Run backstop test

on:
  pull_request:
    branches: [main]

jobs:
  visual-test:
    runs-on: ubuntu-latest
    name: Backstop Test
    steps:
      - uses: actions/checkout@v2
      - uses: ./run-backstop-test
        env:
          ACTIONS_RUNTIME_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}


