name: Run backstop test

on:
  push

jobs:
  visual-test:
    runs-on: ubuntu-latest
    name: Backstop Test
    steps:
      - uses: actions/checkout@v2
      - uses: ./action
#        env:
#          ACTIONS_RUNTIME_TOKEN: ${{secrets.GITHUB_TOKEN}}

