name: Run backstop test

on:
  push

jobs:
  visual-test:
    runs-on: ubuntu-latest
    name: Backstop Test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: action
      - uses: ./action
        with:
          working-directory: action
#        with:
#          path: |
#            backstop_data/html_report/
#            backstop_data/bitmaps_test/
#            backstop_data/bitmaps_reference/
        env:
          ACTIONS_RUNTIME_TOKEN: ${{secrets.GITHUB_TOKEN}}

