name: Run backstop test

on:
  push

jobs:
  visual-test:
    runs-on: ubuntu-latest
    name: Backstop Test
    steps:
      - uses: actions/checkout@v2
      - uses: ../actions/backstop
#      - name: Archive results
#        uses: actions/upload-artifact@v2
#        if: ${{ failure() }}
#        with:
#          name: backstop report
#          path: |
#            backstop_data/html_report/
#            backstop_data/bitmaps_test/
#            backstop_data/bitmaps_reference/
